[Char Widths]
# This is to put a little space around glyphs.  Make sure this is
# an even number, or it'll throw the glyphs off-center.
AdvanceExtraPixels=2
AddToAllWidths=1
Top=5
Baseline=26
LineSpacing=24	// needs to be a multiple of 4 for texel alignment at zoom = 0.5 and screen height = 320

DrawExtraPixelsLeft=2
DrawExtraPixelsRight=2

line 0=0123456789

0=24
1=24
2=24
3=24
4=24
5=24
6=24
7=24
8=24
9=24
