[Layer2]
File=frame
OnCommand=x,SCREEN_CENTER_X;y,SCREEN_CENTER_Y;zoomToWidth,SCREEN_WIDTH;faderight,0.1;fadeleft,0.1;cropright,1.1;cropleft,-0.1;linear,1;cropright,-0.1

[Layer3]
File=flare
InitCommand=
#blend,add
OnCommand=y,SCREEN_CENTER_Y-164;x,SCREEN_LEFT-64;RotationZ,0;Linear,1;x,SCREEN_RIGHT+64;RotationZ,+360;

[Layer4]
File=flare
InitCommand=
#blend,add
OnCommand=y,SCREEN_CENTER_Y+164;x,SCREEN_LEFT-64;RotationZ,0;Linear,1;x,SCREEN_RIGHT+64;RotationZ,-360

[Layer5]
File=../ScreenWithMenuElements underlay
[Layer6]
Type=BitmapText
Text=Welcome to St. Beltina Academy!
File=_eurostile blue glow
InitCommand=X,SCREEN_CENTER_X;Y,SCREEN_CENTER_Y-149;shadowlength,0
OnCommand=horizalign,center;Zoom,.5
[Layer7]
Type=BitmapText
Font=_v profile
Text=Play modcharts with common settings.
OnCommand=X,SCREEN_CENTER_X-141;Y,SCREEN_CENTER_Y-112;Zoom,0.3;ShadowLength,1;HorizAlign,Left;DiffuseShift;EffectColor1,#00DD00;EffectColor2,#00DD00
[Layer8]
Type=BitmapText
Font=_v profile
Text=Explore other arcade game modes of In The Groove.
OnCommand=X,SCREEN_CENTER_X-109;Y,SCREEN_CENTER_Y-80;Zoom,0.3;ShadowLength,1;HorizAlign,Left;DiffuseShift;EffectColor1,#DD0000;EffectColor2,#DD0000
[Layer9]
Type=BitmapText
Font=_v profile
Text=Casual courses usually consisting of 4 songs.
OnCommand=X,SCREEN_CENTER_X-77;Y,SCREEN_CENTER_Y-48;Zoom,0.3;ShadowLength,1;HorizAlign,Left;DiffuseShift;EffectColor1,#DDDD00;EffectColor2,#DDDD00
[Layer10]
Type=BitmapText
Font=_v profile
Text=Study existing charts, or choreograph your own!
OnCommand=X,SCREEN_CENTER_X-45;Y,SCREEN_CENTER_Y-16;Zoom,0.3;ShadowLength,1;HorizAlign,Left;DiffuseShift;EffectColor1,#BBBBBB;EffectColor2,#BBBBBB
[Layer11]
Type=BitmapText
Font=_v profile
Text=Where all the game's settings live.
OnCommand=X,SCREEN_CENTER_X-13;Y,SCREEN_CENTER_Y+16;Zoom,0.3;ShadowLength,1;HorizAlign,Left;DiffuseShift;EffectColor1,#BBBBBB;EffectColor2,#BBBBBB
[Layer12]
Type=BitmapText
Font=_v profile
Text=Close the game.
OnCommand=X,SCREEN_CENTER_X+19;Y,SCREEN_CENTER_Y+48;Zoom,0.3;ShadowLength,1;HorizAlign,Left;DiffuseShift;EffectColor1,#660000;EffectColor2,#660000