[Layer2]
File=frame
OnCommand=x,SCREEN_CENTER_X;y,SCREEN_CENTER_Y;zoomToWidth,SCREEN_WIDTH;faderight,0.1;fadeleft,0.1;cropright,1.1;cropleft,-0.1;linear,1;cropright,-0.1

[Layer3]
File=flare
InitCommand=
#blend,add
OnCommand=y,SCREEN_CENTER_Y-164;x,SCREEN_LEFT-64;RotationZ,0;Linear,1;x,SCREEN_RIGHT+64;RotationZ,+360;

[Layer4]
File=flare
InitCommand=
#blend,add
OnCommand=y,SCREEN_CENTER_Y+164;x,SCREEN_LEFT-64;RotationZ,0;Linear,1;x,SCREEN_RIGHT+64;RotationZ,-360

[Layer5]
File=../ScreenWithMenuElements underlay
[Layer6]
Type=BitmapText
Text=Welcome to St. Beltina Academy!
File=_eurostile blue glow
InitCommand=X,SCREEN_CENTER_X;Y,SCREEN_CENTER_Y-149;shadowlength,0
OnCommand=horizalign,center;Zoom,.5
[Layer7]
Type=BitmapText
Font=_v profile
Text=The standard mode.  Pick songs, play them.
OnCommand=X,SCREEN_CENTER_X-141;Y,SCREEN_CENTER_Y-112;Zoom,0.3;ShadowLength,1;HorizAlign,Left;DiffuseShift;EffectColor1,#00DD00;EffectColor2,#00DD00
[Layer8]
Type=BitmapText
Font=_v profile
Text=2 dancers attack each other with mods.
OnCommand=X,SCREEN_CENTER_X-109;Y,SCREEN_CENTER_Y-80;Zoom,0.3;ShadowLength,1;HorizAlign,Left;DiffuseShift;EffectColor1,#DD0000;EffectColor2,#DD0000
[Layer9]
Type=BitmapText
Font=_v profile
Text=Serious courses that demand you do well to earn time.
OnCommand=X,SCREEN_CENTER_X-77;Y,SCREEN_CENTER_Y-48;Zoom,0.3;ShadowLength,1;HorizAlign,Left;DiffuseShift;EffectColor1,#3333DD;EffectColor2,#3333DD