# FFT font, lovingly placed togather over top of some other font.

[main]
AdvanceExtraPixels=0
DrawExtraPixelsLeft=0
DrawExtraPixelsRight=0
Top=2
Baseline=20
LineSpacing=20

line 0= 9
line 1=0%
line 2=1.
line 3=2?
line 4=3s
line 5=4t
line 6=5n
line 7=6d
line 8=7r
line 9=8h


0=10
1=10
2=10
3=10
4=10
5=10
6=10
7=10
8=10
9=10
10=10
11=10
12=10
13=10
14=10
15=10
16=10
17=10
18=10
