# Non-doubles only:
[Layer1]
Type=Quad
Cond=not GAMESTATE:PlayerUsingBothSides()
OnCommand=faderight,.1;stretchto,SCREEN_LEFT,SCREEN_TOP,SCREEN_CENTER_X,SCREEN_BOTTOM;diffuseshift;EffectColor1,1,0,0.24,0.3;EffectColor2,1,0,0,0.9

# Doubles only:
[Layer3]
Type=Quad
Cond=GAMESTATE:PlayerUsingBothSides()
OnCommand=faderight,.1;fadeleft,.1;stretchto,SCREEN_LEFT,SCREEN_TOP,SCREEN_RIGHT,SCREEN_BOTTOM;diffuseshift;EffectColor1,1,0,0.24,0.3;EffectColor2,1,0,0,0.9

[Layer5]
Type=Quad
InitCommand=%function(self) self:zoom(0) if not Danger then Danger = {} end Danger[1] = self end
